const content = {
    uz: {
        heading: "Qilinadigan ishlar ro'yhati",
        theme1: "Yorug' fon",
        theme2: "Qorong'u fon",
        sorttype1: "Barcha",
        sorttype2: "Tugallangan",
        sorttype3: "Tugallanmagan",
        createBtn: "Qo'shish",
        editBtn: "Tahrirlash",
        deleteBtn: "O'chirish",
        modalTitle: "Rostan ham o'chirmoqchimisiz?",
        modalText: "Agar o'chirsangiz butunlayga yo'qoladi",
        modalCancelBtn: "Bekor qilish",
        modaldeleteBtn: "O'chirish",
    },
    en: {
        heading: "Todo List",
        theme1: "LightMode",
        theme2: "DarkMode",
        sorttype1: "All",
        sorttype2: "Completed",
        sorttype3: "Uncompleted",
        createBtn: "Add",
        editBtn: "Edit",
        deleteBtn: "Delete",
        modalTitle: "Really you want to delete?",
        modalText: "If you delete you can't see it anymore",
        modalCancelBtn: "Cancel",
        modaldeleteBtn: "Delete",
    },
    ru: {
        heading: "Список дела",
        theme1: "Яркий фон",
        theme2: "Темный фон",
        sorttype1: "Все",
        sorttype2: "Завершенный",
        sorttype3: "Незавершенный",
        createBtn: "Добавить",
        editBtn: "Tahrirlash",
        deleteBtn: "Удалить",
        modalTitle: "Вы действительно хотите удалить?",
        modalText: "Если ты удалишь, то больше не увидишь",
        modalCancelBtn: "Отменить",
        modaldeleteBtn: "Удалить",
    },
}
export default content